name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: syedshahidashiqali/solutia-reservation-assessment
      TAG: ${{ github.run_number }}  # consistent tag across steps

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
